/**
 * 대한민국 2022 개정 초등 교육과정 기준 학년별 빠른 설정 (Presets)
 */
import { WorksheetRule } from './types';

export interface PresetItem {
  id: string;
  grade: string; // "초등학교 1학년", "초등학교 2학년" 등
  gradeShort: string; // "초1", "초2"
  title: string; // "2학년 받아올림 덧셈"
  description: string;
  rule: WorksheetRule;
}

export const GRADE_PRESETS: PresetItem[] = [
  {
    id: 'g1-add-sub-basic',
    grade: '초등학교 1학년',
    gradeShort: '초1',
    title: '1학년 한 자리 수 덧셈과 뺄셈',
    description: '받아올림과 받아내림 없이 10 이하 및 한 자리 수의 기본 덧셈·뺄셈을 연습합니다.',
    rule: {
      schemaVersion: 1,
      title: '1학년 한 자리 수 덧셈과 뺄셈',
      operations: ['addition', 'subtraction'],
      count: 20,
      operandA: { digits: [1], allowZeroEnding: true },
      operandB: { digits: [1], allowZeroEnding: true },
      carryCondition: 'none',
      borrowCondition: 'none',
      divisionCondition: 'none',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'commutative',
      displayFormat: 'horizontal',
      showFirstExample: true,
    },
  },
  {
    id: 'g2-add-carry-once',
    grade: '초등학교 2학년',
    gradeShort: '초2',
    title: '2학년 받아올림이 있는 두 자리 수 덧셈',
    description: '일의 자리에서 십의 자리로 받아올림이 정확히 한 번 발생하는 두 자리 수 덧셈입니다.',
    rule: {
      schemaVersion: 1,
      title: '2학년 두 자리 수 덧셈 (받아올림 한 번)',
      operations: ['addition'],
      count: 20,
      operandA: { digits: [2], allowZeroEnding: true },
      operandB: { digits: [1, 2], allowZeroEnding: true },
      carryCondition: 'once',
      borrowCondition: 'any',
      divisionCondition: 'none',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'exact',
      displayFormat: 'vertical',
      showFirstExample: true,
    },
  },
  {
    id: 'g2-sub-borrow-once',
    grade: '초등학교 2학년',
    gradeShort: '초2',
    title: '2학년 받아내림이 있는 두 자리 수 뺄셈',
    description: '십의 자리에서 일의 자리로 받아내림이 한 번 필요한 두 자리 수 뺄셈을 집중 연습합니다.',
    rule: {
      schemaVersion: 1,
      title: '2학년 두 자리 수 뺄셈 (받아내림 한 번)',
      operations: ['subtraction'],
      count: 20,
      operandA: { digits: [2], allowZeroEnding: true },
      operandB: { digits: [1, 2], allowZeroEnding: true },
      carryCondition: 'any',
      borrowCondition: 'once',
      divisionCondition: 'none',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'exact',
      displayFormat: 'vertical',
      showFirstExample: true,
    },
  },
  {
    id: 'g2-multiplication-table',
    grade: '초등학교 2학년',
    gradeShort: '초2',
    title: '2학년 곱셈구구 (2단~9단)',
    description: '초등 2학년 2학기 핵심인 2단부터 9단까지의 곱셈구구를 고르게 익힙니다.',
    rule: {
      schemaVersion: 1,
      title: '2학년 곱셈구구 (2단~9단)',
      operations: ['multiplication'],
      count: 20,
      operandA: { digits: [1], allowZeroEnding: true },
      operandB: { digits: [1], allowZeroEnding: true },
      carryCondition: 'any',
      borrowCondition: 'any',
      divisionCondition: 'none',
      multiplicationRule: {
        minDan: 2,
        maxDan: 9,
        includeZeroOne: false,
        allowReverseCommutative: false,
      },
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'commutative',
      displayFormat: 'horizontal',
      showFirstExample: true,
    },
  },
  {
    id: 'g3-add-sub-three-digits',
    grade: '초등학교 3학년',
    gradeShort: '초3',
    title: '3학년 세 자리 수 덧셈과 뺄셈',
    description: '받아올림과 받아내림이 있는 세 자리 수의 덧셈과 뺄셈을 세로셈으로 정확하게 계산합니다.',
    rule: {
      schemaVersion: 1,
      title: '3학년 세 자리 수 덧셈과 뺄셈',
      operations: ['addition', 'subtraction'],
      count: 20,
      operandA: { digits: [3], allowZeroEnding: true },
      operandB: { digits: [2, 3], allowZeroEnding: true },
      carryCondition: 'any',
      borrowCondition: 'any',
      divisionCondition: 'none',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'exact',
      displayFormat: 'vertical',
      showFirstExample: true,
    },
  },
  {
    id: 'g3-division-exact',
    grade: '초등학교 3학년',
    gradeShort: '초3',
    title: '3학년 나머지가 없는 나눗셈',
    description: '두 자리 수를 한 자리 수로 나누어떨어지게 계산하는 기초 나눗셈입니다.',
    rule: {
      schemaVersion: 1,
      title: '3학년 나머지가 없는 나눗셈',
      operations: ['division'],
      count: 20,
      operandA: { digits: [2], allowZeroEnding: true },
      operandB: { digits: [1], allowZeroEnding: false },
      carryCondition: 'any',
      borrowCondition: 'any',
      divisionCondition: 'none',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'exact',
      displayFormat: 'horizontal',
      showFirstExample: true,
    },
  },
  {
    id: 'g3-division-remainder',
    grade: '초등학교 3학년',
    gradeShort: '초3',
    title: '3학년 나머지가 있는 나눗셈',
    description: '두 자리 수 ÷ 한 자리 수에서 몫과 나머지를 함께 구하는 나눗셈 연습입니다.',
    rule: {
      schemaVersion: 1,
      title: '3학년 나머지가 있는 나눗셈',
      operations: ['division'],
      count: 20,
      operandA: { digits: [2], allowZeroEnding: true },
      operandB: { digits: [1], allowZeroEnding: false },
      carryCondition: 'any',
      borrowCondition: 'any',
      divisionCondition: 'required',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'exact',
      displayFormat: 'horizontal',
      showFirstExample: true,
    },
  },
  {
    id: 'g4-multi-digits-mult-div',
    grade: '초등학교 4학년',
    gradeShort: '초4',
    title: '4학년 (두/세 자리 수) 곱셈과 나눗셈',
    description: '여러 자리 수 곱셈과 두 자리 수로 나누는 나눗셈 연산 실력을 다집니다.',
    rule: {
      schemaVersion: 1,
      title: '4학년 여러 자리 수 곱셈과 나눗셈',
      operations: ['multiplication', 'division'],
      count: 20,
      operandA: { digits: [3], allowZeroEnding: true },
      operandB: { digits: [1, 2], allowZeroEnding: true },
      carryCondition: 'any',
      borrowCondition: 'any',
      divisionCondition: 'mixed',
      allowNegative: false,
      allowZero: false,
      uniqueMode: 'exact',
      displayFormat: 'vertical',
      showFirstExample: true,
    },
  },
];
